# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-30 08:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Author', models.CharField(max_length=30)),
                ('Title', models.CharField(max_length=30)),
                ('Content', models.TextField()),
                ('Timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
