# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-12 08:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_first_blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Styles', models.CharField(max_length=30)),
                ('Services', models.TextField(max_length=100)),
                ('TimeAvailable', models.DateField(max_length=50)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
